[pytest]
testpaths = tests

markers =
    home: selenium tests for the landing page
    favorites: selenium tests for the favorites sidebar
    words: selenium tests for the words tab
    extrainfo: selenium tests for the document extra-info panel
