# Generated by Django 4.2.17 on 2025-11-29 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=128)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True)),
                ('dataset_dir', models.CharField(max_length=128)),
                ('public', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('public_documents', models.BooleanField(default=False)),
                ('authorized_users', models.ManyToManyField(related_name='private_datasets', to=settings.AUTH_USER_MODEL)),
                ('favorite_users', models.ManyToManyField(related_name='favorite_datasets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('filename', models.CharField(max_length=128)),
                ('source', models.URLField(max_length=1000)),
                ('length', models.PositiveIntegerField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='visualize.dataset')),
                ('favorite_users', models.ManyToManyField(related_name='favorite_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('dataset', 'index')},
            },
        ),
        migrations.CreateModel(
            name='ExternalDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True)),
                ('database_settings', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MetadataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('datatype', models.CharField(max_length=64)),
            ],
            options={
                'unique_together': {('name', 'datatype')},
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='visualize.analysis')),
                ('favorite_users', models.ManyToManyField(related_name='favorite_topics', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='visualize.topic')),
            ],
        ),
        migrations.CreateModel(
            name='TopicNameScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordToken',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('token_index', models.PositiveIntegerField()),
                ('start_index', models.PositiveIntegerField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='visualize.analysis')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='visualize.document')),
            ],
        ),
        migrations.CreateModel(
            name='WordType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordTokenTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualize.wordtoken')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualize.topic')),
            ],
            options={
                'unique_together': {('token', 'topic')},
            },
        ),
        migrations.AddField(
            model_name='wordtoken',
            name='word_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='visualize.wordtype'),
        ),
        migrations.AddField(
            model_name='wordtoken',
            name='word_type_abstraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_type_abstraction_tokens', to='visualize.wordtype'),
        ),
        migrations.CreateModel(
            name='TopicWordTypeMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualize.metric')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_type_metric_values', to='visualize.topic')),
                ('word_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_metric_values', to='visualize.wordtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopicPairwiseMetricValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('ending_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ending_metric_values', to='visualize.topic')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualize.metric')),
                ('origin_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='originating_metric_values', to='visualize.topic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopicName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('name_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='visualize.topicnamescheme')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='visualize.topic')),
            ],
            options={
                'unique_together': {('topic', 'name_scheme')},
            },
        ),
        migrations.CreateModel(
            name='TopicMetricValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualize.metric')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_values', to='visualize.topic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopicMetadataValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bool_value', models.BooleanField(blank=True, null=True)),
                ('float_value', models.FloatField(null=True)),
                ('int_value', models.IntegerField(null=True)),
                ('text_value', models.TextField(null=True)),
                ('datetime_value', models.DateTimeField(null=True)),
                ('metadata_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualize.metadatatype')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_values', to='visualize.topic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='topic',
            name='schemes',
            field=models.ManyToManyField(through='visualize.TopicName', to='visualize.topicnamescheme'),
        ),
        migrations.AddField(
            model_name='topic',
            name='tokens',
            field=models.ManyToManyField(related_name='topics', through='visualize.WordTokenTopic', to='visualize.wordtoken'),
        ),
        migrations.CreateModel(
            name='Stopword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualize.analysis')),
                ('word_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualize.wordtype')),
            ],
            options={
                'unique_together': {('analysis', 'word_type')},
            },
        ),
        migrations.CreateModel(
            name='ExcludedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualize.analysis')),
                ('word_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualize.wordtype')),
            ],
            options={
                'unique_together': {('analysis', 'word_type')},
            },
        ),
        migrations.CreateModel(
            name='DocumentPairwiseMetricValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_pairwise_metric_values', to='visualize.analysis')),
                ('ending_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ending_metric_values', to='visualize.document')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualize.metric')),
                ('origin_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origininating_metric_values', to='visualize.document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentMetricValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_values', to='visualize.document')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualize.metric')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentMetadataValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bool_value', models.BooleanField(blank=True, null=True)),
                ('float_value', models.FloatField(null=True)),
                ('int_value', models.IntegerField(null=True)),
                ('text_value', models.TextField(null=True)),
                ('datetime_value', models.DateTimeField(null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_values', to='visualize.document')),
                ('metadata_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualize.metadatatype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentAnalysisMetricValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_analysis_metric_values', to='visualize.analysis')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_analysis_metric_values', to='visualize.document')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualize.metric')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DatasetMetricValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_values', to='visualize.dataset')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualize.metric')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DatasetMetadataValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bool_value', models.BooleanField(blank=True, null=True)),
                ('float_value', models.FloatField(null=True)),
                ('int_value', models.IntegerField(null=True)),
                ('text_value', models.TextField(null=True)),
                ('datetime_value', models.DateTimeField(null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_values', to='visualize.dataset')),
                ('metadata_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualize.metadatatype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnalysisMetricValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_values', to='visualize.analysis')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualize.metric')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnalysisMetadataValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bool_value', models.BooleanField(blank=True, null=True)),
                ('float_value', models.FloatField(null=True)),
                ('int_value', models.IntegerField(null=True)),
                ('text_value', models.TextField(null=True)),
                ('datetime_value', models.DateTimeField(null=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_values', to='visualize.analysis')),
                ('metadata_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualize.metadatatype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='analysis',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='visualize.dataset'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='excluded_words',
            field=models.ManyToManyField(related_name='excluded_word_analyses', through='visualize.ExcludedWord', to='visualize.wordtype'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='favorite_users',
            field=models.ManyToManyField(related_name='favorite_analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysis',
            name='stopwords',
            field=models.ManyToManyField(related_name='stopword_analyses', through='visualize.Stopword', to='visualize.wordtype'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='word_types',
            field=models.ManyToManyField(related_name='word_type_analyses', through='visualize.WordToken', to='visualize.wordtype'),
        ),
        migrations.AlterUniqueTogether(
            name='wordtoken',
            unique_together={('analysis', 'document', 'token_index')},
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_hash', models.CharField(max_length=128)),
                ('url', models.URLField(max_length=10000)),
                ('favorite_users', models.ManyToManyField(related_name='favorite_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('url_hash', 'url')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('analysis', 'number')},
        ),
        migrations.CreateModel(
            name='IPAddresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=128)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualize.counttype')),
            ],
            options={
                'unique_together': {('type', 'ip_address')},
            },
        ),
        migrations.CreateModel(
            name='CountValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualize.counttype')),
            ],
            options={
                'unique_together': {('type', 'timestamp')},
            },
        ),
    ]
