# Generated by Django 5.2.17 on 2026-09-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='word_types',
            field=models.ManyToManyField(related_name='word_type_analyses', through='visualize.WordToken', through_fields=('analysis', 'word_type'), to='visualize.wordtype'),
        ),
    ]
